name: pkg-size

on:
  pull_request:
    branches: [ master, develop ] # â¬… Add other branches you want size checks on

jobs:
  pkg-size:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]
    
    steps:
    - uses: actions/checkout@v3

    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    
    - name: Install lastest stable rust
      uses: actions-rs/toolchain@v1
      with:
            toolchain: stable
            override: true
            components: rustfmt, clippy
    
    - uses: jetli/wasm-pack-action@v0.3.0
      with:
        # Optional version of wasm-pack to install(eg. 'v0.9.1', 'latest')
        version: 'latest'

    - uses: Swatinem/rust-cache@v1
      with:
        working-directory: ./wasm
    
    - name: pnpm cache
      uses: actions/cache@v3
      with:
        path: |
          /home/runner/.pnpm-store
        key: ${{ runner.os }}-${{ hashFiles('**/pnpm-lock.yaml') }}

    - name: install pnpm
      run: |
        npm install -g pnpm
        
    - name: WASM Compile
      run: |
        pnpm wasm
        
    - name: install dependency
      run: |
        pnpm install
        
    - name: Package
      run: |
        pnpm build
        
    - name: Package size report
      uses: pkg-size/action@v1
      with:
        build-command: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        
        
